### ISSUE TITLE
mac上运行iphoneBot一直出错

### ISSUE THREAD

**Issue by vincentwzc** [charlie-captain/iPhone-bot#4]
<img width="559" alt="image" src="https://github.com/charlie-captain/iPhone-bot/assets/147279772/b430bdff-41c2-4f91-8004-adc3be0e9040">

**Comment by vincentwzc** [comment]
求大佬解答

**Comment by charlie-captain** [comment]
下载一下settings.json，配置一下

**Comment by Jackie1017** [comment]
同Mac 同报错，求救大佬

**Comment by vincentwzc** [comment]
settings.json下载了也配置了，但是如果是在iPhone-bot-main文件夹内就是no such file or directory，拉到users文件夹里面就是读取不出来

**Comment by Jackie1017** [comment]
我也是同样问题 求救大佬

**Comment by charlie-captain** [comment]
检查一下json格式有没有问题，看报错是解析出错了；
程序和json文件放在一个文件夹内就行

**Comment by Jackie1017** [comment]
已解决，谢谢大佬。json里面格式错了。
